services:
  - type: web
    name: anonymous-ctf
    env: node
    plan: free
    buildCommand: |
      npm install
      npm rebuild sqlite3
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
